version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  deploy:
    parameters:
      bucket:
        type: string
    working_directory: ~/repo

    docker:
      - image: cimg/node:lts

    resource_class: xlarge
    steps:
      - checkout
      - aws-cli/install

      - run:
          name: Yarn Install
          command: yarn install --network-timeout 1000000

      - run:
          name: Gatsby build
          command: yarn build;

      - run:
          name: AWS S3 Sync
          command: aws s3 sync public/ <<parameters.bucket>> --delete

  deploy-dev:
    - deploy:
      bucket: 's3://dev-biosecurity'

      # - run:
      #     name: Run cloudfront invalidation
      #     command: |
      #       aws cloudfront create-invalidation \
      #       --distribution-id E1K4CMH3A58OPJ \
      #       --paths "/*"

workflows:
  version: 2
  build:
    jobs:
      - deploy-dev:
          filters:
            branches:
              only:
                - circleci
          context:
            - AWS Credentials
            - Airtable Credentials
      # - deploy-review:
      #     filters:
      #       branches:
      #         only:
      #           - review
      #     context:
      #       - AWS Credentials
      # - deploy-staging:
      #     filters:
      #       branches:
      #         only:
      #           - staging
      #     context:
      #       - AWS Credentials
      # - deploy-prod:
      #     filters:
      #       branches:
      #         only:
      #           - prod
      #     context:
      #       - AWS Credentials
