version: 2.1

credentials: &credentials
  - AWS Credentials
  - Airtable Credentials

workflows:
  version: 2
  build:
    jobs:
      # dev site
      - deploy:
          bucket: 's3://dev-biosecurity'
          distribution: 'E31RJZOJBZKNK7'
          context: *credentials
          filters:
            branches:
              only:
                - dev
      # review site
      - deploy:
          bucket: 's3://review-biosecurity'
          distribution: 'E1C3POE3SNNT13'
          context: *credentials
          filters:
            branches:
              only:
                - review
      # staging site
      - deploy:
          bucket: 's3://staging-biosecurity'
          distribution: 'E2Y1HDO9J5FPR9'
          context: *credentials
          filters:
            branches:
              only:
                - staging
      # prod site
      - deploy:
          bucket: 's3://prod-biosecurity'
          distribution: 'E225RTJBB12HS1'
          context: *credentials
          filters:
            branches:
              only:
                - prod

orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  deploy:
    docker:
      - image: cimg/node:lts

    resource_class: xlarge

    working_directory: ~/repo

    parameters:
      bucket:
        type: string
      distribution:
        type: string

    steps:
      - checkout
      - aws-cli/install

      - run:
          name: Check container ubuntu version
          command: lsb_release -a

      - run:
          name: Install binary dependencies for `node-canvas`
          command: |
            sudo apt-get update
            sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - restore_cache:
          keys:
            - yarn-deps-{{ checksum "yarn.lock" }}
            - yarn-deps-

      - run:
          name: Yarn Install
          command: yarn install --network-timeout 1000000

      - run:
          name: Gatsby clean
          command: yarn run gatsby clean

      - run:
          name: Gatsby build
          command: yarn build;

      - run:
          name: AWS S3 Sync to <<parameters.bucket>>
          command: aws s3 sync public/ <<parameters.bucket>> --delete

      - run:
          name: Run cloudfront invalidation
          command: |
            aws cloudfront create-invalidation \
            --distribution-id <<parameters.distribution>> \
            --paths "/*"

      - save_cache:
          key: yarn-deps-{{ checksum "yarn.lock" }}
          paths:
            - 'node_modules'
            - '.cache'
            - 'public'
