version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

jobs:
  deploy-prod:
    working_directory: ~/repo

    docker:
      - image: cimg/node:14.4

    steps:
      - checkout

      - run:
          name: Installing Deployment Dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y install python3-pip python3-dev g++ build-essential
            pip3 install --upgrade pip
            sudo apt-get remove python-pip
            pip3 install --upgrade setuptools pytz
            pip3 install awsebcli==3.10.0
            pip3 install boto3

      - aws-cli/install
      - aws-cli/configure

      - run:
          name: Build
          command: rm yarn.lock; yarn install --network-timeout 1000000

      - run:
          name: Deploy
          command: yarn run deploy

      - run:
          name: Create Invalidation
          command: |
            aws cloudfront create-invalidation \
              --distribution-id E1AFIMCMLQ96KB \
              --paths "/*"


  deploy-test:
    working_directory: ~/repo

    docker:
      - image: cimg/node:14.4

    steps:
      - checkout

      - run:
          name: Installing Deployment Dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y install python3-pip python3-dev g++ build-essential
            pip3 install --upgrade pip
            sudo apt-get remove python-pip
            pip3 install --upgrade setuptools pytz
            pip3 install awsebcli==3.10.0
            pip3 install boto3

      - aws-cli/install
      - aws-cli/configure

      - run:
          name: Build
          command: rm yarn.lock; yarn install --network-timeout 1000000

      - run:
          name: Deploy
          command: yarn run deploy-test

      - run:
          name: Create Invalidation
          command: |
            aws cloudfront create-invalidation \
              --distribution-id E1BA40SS45JOPH \
              --paths "/*"


workflows:
  version: 2
  build:
    jobs:
      - deploy-prod:
          filters:
            branches:
              only:
                - master
      - deploy-test:
          filters:
            branches:
              only:
                - dev
